; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
board_microros_transport = serial
board_microros_distro = jazzy
monitor_speed = 115200
lib_deps = 
	https://github.com/micro-ROS/micro_ros_platformio
	gin66/FastAccelStepper@^0.34.0
	janelia-arduino/TMC2209@^10.1.1

; [env:esp32dev]
; platform = espressif32
; board = esp32dev
; framework = arduino

; [env:pico]
; platform = raspberrypi
; board = pico
; framework = arduino

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
build_flags =
	 -D ARDUINO_USB_CDC_ON_BOOT=1
	;  -U ARDUINO_USB_MODE
     -D CORE_DEBUG_LEVEL=5           ; Enables INFO level logs

; [env:esp32c3]
; platform = espressif32
; board = seeed_xiao_esp32c3
; framework = arduino
